### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by danbroooks** [ministryofjustice/date-utils#15]
Any chance we could get some fresh tags added pointing to a more recent commit? I'd like to use this library but don't want to use `dev-master`, and the latest tag is a year old and broken.

Thanks

**Comment by eddiejaoude** [comment]
Is `v0.31.1` really broke?

@knasher can you look into this?

**Comment by danbroooks** [comment]
Sorry 'broken' is over exaggerating it a bit, but 0.31 returns some incorrect bank holidays. When I loaded in dev-master, the expected bank holidays are loaded

**Comment by brettminnie** [comment]
Which ones are incorrect may I ask?

@eddiejaoude I think we can still tag but not sure of dependancies being
used by the team

**Comment by jeremyquinton** [comment]
@danbroooks released tag for you 0.4.0

**Comment by eddiejaoude** [comment]
> Which ones are incorrect may I ask?

@danbroooks Good to log this against the previous tag to make people aware (thanks @brettminnie )

Nice one @jeremyquinton

**Comment by danbroooks** [comment]
Sorry I wasn't sure how much tags were actually being used seeing as there were only three made in fairly quick succession this time last year.

Just off the top of my head I think 0.31.0 was coming back with Boxing Day this year being on the 26th (a saturday), whereas for my purposes I wanted it to be the next working day, the 28th. `master` returns Boxing Day as being on the 28th.

**Comment by danbroooks** [comment]
Thanks for the tag, however perhaps [give this a read](http://semver.org/). The tag added was 0.4.0, however previous tags have been 0.18.1, 0.21.1 and 0.31.1. 

To composer the latest tag is actually the oldest version of the four. Those putting "ministryofjustice/date-utils": "~0.4" in their `composer.json` will end up getting 0.31, which is actually older than this most recent tag.

**Comment by eddiejaoude** [comment]
Well noticed @danbroooks .

`0.4` is old than `0.31`.

`0.31.*` could be deleted, but I remember packagist didn't delete old tags before, which also caused issues in the past.

Is it worth bumping the major @jeremyquinton and starting again? eg. `1.0.0` and go from there

**Comment by danbroooks** [comment]
Yes I would keep existing tags in place (however perhaps drop `0.4.0` before people pick it up), then either bump to `1.0.0` or increment `0.31.*` until you are ready to commit to a `1.0.0` version.

**Comment by brettminnie** [comment]
The old tags where pre-release.sprint number.revision. So yes could be
considered a release now

@jeremyquinton :+1: for picking this up, I'll look at the fix for the
reported problem for the 0.31.x branch as well seeing as I am on whoreliday
:)

B

**Comment by jeremyquinton** [comment]
@danbroooks well spotted. I have released tag 1.0.0. This library is stable enough to be version 1.0.0. 

Should I delete the 0.4.0 tag I created or is it going to create issues?

**Comment by eddiejaoude** [comment]
I would delete `0.4` as it is newer than `0.31` which is more confusing.

Everyone will probably use `1.0` now anyway as it is the latest stable.

**Comment by brettminnie** [comment]
Agree with Eddie here

**Comment by jeremyquinton** [comment]
I deleted 0.4.0 and created a 1.0.0 tag
