### ISSUE TITLE
No license?

### ISSUE THREAD

**Issue by Brunty** [ministryofjustice/date-utils#19]
Hi,

This project doesn't have a license, which (to my understanding) means it's not usable in projects.

Is it not an open source package usable by others, or is it just an oversight? :)

https://choosealicense.com/no-license/

**Comment by eddiejaoude** [comment]
License add in PR and merged https://github.com/ministryofjustice/date-utils/pull/21

**Comment by Brunty** [comment]
PR was closed, not merged?

**Comment by eddiejaoude** [comment]
Sorry I was looking quickly on my phone. You are right, it was **closed** not **merged** 👍
