### ISSUE TITLE
Use the GOV.UK bank holiday feed?

### ISSUE THREAD

**Issue by jystewart** [ministryofjustice/date-utils#2]
Calculating bank holidays is a complex business. As an example see the discussions on:

https://github.com/alphagov/calendars/pull/74
https://github.com/alphagov/calendars/pull/1

You might be better off using the GOV.UK bank holiday iCal feed https://www.gov.uk/bank-holidays/england-and-wales.ics (there's also a JSON equivalent but the iCal version is supported whereas the JSON version isn't)

**Comment by knasher** [comment]
Updated for substitute days and removed dependency on timestamps, closing issue.
