### ISSUE TITLE
Zend framework dependency

### ISSUE THREAD

**Issue by aranw** [ministryofjustice/date-utils#6]
I was just wondering why is there a dev dependency on zendframework for this package? 

Also why does the BankHolidays.php file have a use statement for a zend class? https://github.com/ministryofjustice/date-utils/blob/master/src/DateUtils/BankHolidays.php#L5

**Comment by eddiejaoude** [comment]
That might be a mistake. As it is not used in the file nor is it in as a `composer` include:
https://github.com/ministryofjustice/date-utils/blob/master/composer.json#L5

/cc @brettminnie ?

**Comment by eddiejaoude** [comment]
@aranw thanks for noticing. 

Now fixed :+1:
